# Generated by Django 5.2 on 2025-05-05 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('assignee', models.CharField(blank=True, max_length=100)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('labels', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
